upd: do not allow publish if there are uncommitted changes

diff --git a/ctl/ctl b/ctl/ctl
--- a/ctl/ctl
+++ b/ctl/ctl
@@ -243,6 +243,12 @@ ctl_publish_command() {
 	# src/publish_command.sh
 	# shellcheck shell=bash
 
+	# We do not want to proceed with publishing if there are uncommitted changes.
+	if [ -n "$(git status --porcelain)" ]; then
+		echo "unable to publish as there are uncommitted changes"
+		exit 1
+	fi
+
 	npm run publish
 
 }
